FROM node:14.3.0
LABEL AUTHOR="SOHAM MONDAL <soham.pf.mondal@gmail.com"

ARG PORT=3000
ENV NUXT_HOST=0.0.0.0
ENV APP_ROOT=/usr/src/service

WORKDIR ${APP_ROOT}

COPY package*.json ./

RUN npm ci --only=production

COPY . .

RUN npm run build

EXPOSE ${PORT}